### ISSUE TITLE
Integrate with acm-core

### ISSUE THREAD

**Issue by harshasrikara** [acmutd/TrackIT#83]
**Connect to acm-core**
Ability to export and import from acm-core

**Task List**
 - [ ] cloud function to save event data upon workshop completion
 - [ ] cloud function that would receive information from acm-core
 - [ ] retrieve profile information from acm-core when user signs in

**Additional context**
Integrate effectively with acm-core
