### ISSUE TITLE
Cloud storage for documents

### ISSUE THREAD

**Issue by harshasrikara** [acmutd/TrackIT#84]
**Add files**
Add documents for workshop levels in addition to text

**Task List**

 - [ ] Setup cloud storage
 - [ ] Add UI to save a file and remove a file that the user has added
 - [ ] Add UI to display files that the user has uploaded for a workshop level
 - [ ] User side display link to download file (or maybe an icon that represents file type for a clean look)
 - [ ] Allow admin to set a name for the file they uploaded which can be displayed instead of a link

**Additional context**
Files can be anything --> powerpoints, pdfs, etc
